# with ragular of arm64
## start:: docker-compose up 
## stop:: docker-compose down
## build:: docker-compose build

version: '3' 

services:
  market-server:
    image: public.ecr.aws/r1h0y2m2/test:market-server
    ports:
      - "8000:8000"

  market-front:
    # image: market-front:latest
    image: public.ecr.aws/r1h0y2m2/test:market-front
    ports:
      - "80:3000"
